### model
model_name_or_path: NeverSleep/Lumimaid-v0.2-70B

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
deepspeed: examples/deepspeed/ds_z3_offload_config.json

### dataset
dataset: iggy_cot_sharegpt
template: llama3
cutoff_len: 8192
max_samples: 20000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /home/azureuser/.cache/huggingface/v1_lumi_iggy_cot_11_15
logging_steps: 1
save_steps: 4
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 5.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.05
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 4
